### ISSUE TITLE
Recharge cooldown modifiers are not displayed in component stats

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#10]
The ship's own recharge cooldown values are not displayed in constructor ship info window either.

**Comment by juh9870** [comment]
Relevant fixes from the other repo:
https://github.com/PavelZinchenko/event_horizon/commit/7c1f073decdc6099220adf83a3489b2170d0a736
https://github.com/PavelZinchenko/event_horizon/commit/c681e65ff311c767b1db626de7b45530de5f53a1
