### ISSUE TITLE
Game bugging on starting a new playthrough

### ISSUE THREAD

**Issue by Pomeha-TLA** [PavelZinchenko/event-horizon-main#101]
When attempting to start a new game from the main menu with no save loaded OR after deleting existing save from the menu settings, nothing happens after selecting "New Game" option

**Comment by PavelZinchenko** [comment]
Can't reproduce the bug. Which version did you use?

**Comment by Pomeha-TLA** [comment]
Android latest available on GitHub
Build 1546

**Comment by CrispyToken** [comment]
It appears to be a mod-specific bug to me, could not reproduce with original game loaded, only with a few specific mods.
The one I can currently reproduce it with is Mutant Ships mod, but this may vary.
First, I deleted the existing save from the game main menu settings with this mod loaded, then attempted to start a new game.
Once the bug happens, loading any other save also fails, no matter if a mod or original game and fixing it requires a game relaunch.
Build #1546.

**Comment by Pomeha-TLA** [comment]
Fixed
