### ISSUE TITLE
Component descriptions are not functional

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#11]
Option for descriptions for components exists but does nothing.

**Comment by juh9870** [comment]
Relevant commits:
Initial commit: https://github.com/PavelZinchenko/event_horizon/commit/dc0c0f687e9f4cc9aac6e8f160ce160129e1cc59
Fix: https://github.com/PavelZinchenko/event_horizon/commit/4569127d5c6fb2906fe609fec07af28c58e58591
