### ISSUE TITLE
Issues with quest random

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#12]
The same galaxy node always has same random seed in quests spawned on that node.
Random nodes in the same quest all have same seed.
Manual quests use the same seed as the quest that starts them, they should take a real random seed instead.
Any nodes or requirements in a quest that have random in them, always yield the same random result, because they use the parent quest's fixed seed.
Same goes for loot files with random using a quest's fixed seed always yielding same random result.

**Comment by PavelZinchenko** [comment]
The idea behind having a fixed seed for quests is totally to make sure that if you reload a game, everything happens the same way. It makes the tactic of saving and reloading the game to obtain a specific outcome futile.
But if someone replays a quest in the same spot after finishing it, the seed should change. Also the seed is different for different saves.

**Comment by GreyCardinal69** [comment]
While that is true that is a great issue, if a quest has several random nodes, because of the fixed seed they always pick the same outcome, that same outcome also applies to any loot that has random inside it. Same thing applies to RandomStar condition, and all manual quests started from this quest also have same seed. This limits what can be done with quests greatly and also makes quest harder to work with. Perhaps make it so that the seed remains the same, but changes after each node, condition or anything that uses random. Manual type quests must also be given a different seed.

**Comment by juh9870** [comment]
I can see two solutions:
## `Push Random Seed` and `Pop Random Seed` nodes
When you use `Push Random Seed` node, a new seed is pushed onto the "RNG Stack", and all RNG-based nodes will use that, until `Pop Random Seed` is used, at which point all random nodes will go back to using the previously set seed.

Mod maker can either specify a string to be used in  `Push Random Seed` node, or they can leave it empty for a completely random seed to be pushed.

The actual seed used for RNG nodes is calculated by combining all seeds from the stack with the quest initial seed.

## `Set Random` node
This is similar to the previous suggestion, but "stack" height is only 1, to reduce complexity at the cost of reduced functionality. `Set Random` node will just replace the previously set seed with a new one. Ofc, it still takes quest initial seed into account.

I would love to hear some feedback on what @GreyCardinal69 prefers too.

**Comment by GreyCardinal69** [comment]
I full random seeds for nodes, conditions and whatnot is not possible, then Juh's Set Random node solution is the next best way. That node would take a string as the seed, but if the string is empty a full random seed should be taken.

**Comment by juh9870** [comment]
The issue with full random is that it's less controllable. For a lot of use cases, it's still desirable to have consistent results (faction quests, fleets, loot, etc.)

**Comment by PavelZinchenko** [comment]
I've slightly improved the algorithm for calculating the seed for a quest by taking into account the times this quest was completed. I've also added a UseRandomSeed option, making the seed random for this quest and any quest it starts.
