### ISSUE TITLE
It is possible to scrap quest items with 0 price.

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#120]
Previously, items with no defined price could not be sold in stores or scrapped from inventory.
They can now be scrapped from inventory however for 1 credit.

![image](https://github.com/PavelZinchenko/event-horizon-main/assets/61762578/0a15136b-093c-4c80-9b2c-e81c6d1dc763)

**Comment by PavelZinchenko** [comment]
#2851f20

**Comment by PavelZinchenko** [comment]
2851f20
