### ISSUE TITLE
Impossible to create no-layout modules

### ISSUE THREAD

**Issue by Pomeha-TLA** [PavelZinchenko/event-horizon-main#133]
Due to one of the latest commits its now impossible to make modules with no layout

**Comment by PavelZinchenko** [comment]
It was the bug in the first place that you were able to create such modules. Why do you need them?

**Comment by CrispyToken** [comment]
Additional context:

Modules without a defined layout were widely used by mod developers for the following purposes:
- Providing ships with base statistics that can only be given by modules, without taking up ship slots
- Providing unique visuals without taking up slots
- Infinite stackability without slot usage

These were considered important features and these modules were able to provide them.

**Comment by PavelZinchenko** [comment]
d560105
