### ISSUE TITLE
Game not saving progress in vanilla

### ISSUE THREAD

**Issue by Pomeha-TLA** [PavelZinchenko/event-horizon-main#135]
![Screenshot_20240118-121536](https://github.com/PavelZinchenko/event-horizon-main/assets/152905218/f88ae594-8798-4123-9362-77462484e694)
![Screenshot_20240118-121507](https://github.com/PavelZinchenko/event-horizon-main/assets/152905218/bd9a9d8e-744d-4733-965c-3fbb69a8fd8b)
![Screenshot_20240118-121519](https://github.com/PavelZinchenko/event-horizon-main/assets/152905218/42a4380c-c1bd-4336-be0d-6e1f00dd97c7)
I have a ship
I sold it
I reloaded the game and ship is still here
Affects absolutely all stuff like clearing nodes, buying stuff in shops and etc

**Comment by PavelZinchenko** [comment]
Can't reproduce the bug. Is it PC or Android version? Could you please provide a savegame file?

**Comment by PavelZinchenko** [comment]
Could you attach it here or send by email?

**Comment by Pomeha-TLA** [comment]
No
For some reason both github and email doesn't allows me to send it. I'll just close it for now as its only me who has this problem and save reset fixes this problem
