### ISSUE TITLE
Battles often cause game to lag and freeze up

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#140]
On the latest published pre-release build (#1589, android), even small battles have the potential to make the game lag and slow to a crawl, even if player does nothing.

Example (original game) battle setup that produces lag:
![image](https://github.com/PavelZinchenko/event-horizon-main/assets/61762578/c700d2ed-4763-40ac-aafb-aaad76763eb3)

Entering battle, calling all enemies and then simply waiting is likely to make the issue appear.

**Comment by PavelZinchenko** [comment]
I fixed a couple of similar bugs in the latest build. It's probably one of them. Could you please check?

**Comment by CrispyToken** [comment]
Issue resolved in pre-release build #1595.
Closing.
