### ISSUE TITLE
The database editor is not working

### ISSUE THREAD

**Issue by Kipyatochkov** [PavelZinchenko/event-horizon-main#145]
The database editor that you posted (https://github.com/PavelZinchenko/event-horizon-main/releases/download/v1.10.4/DatabaseEditor.zip) doesn't work. Here are some screenshots: 
![image](https://github.com/PavelZinchenko/event-horizon-main/assets/65084389/b539ae72-00b4-4dc2-9f18-6c849cc7b476)
![image](https://github.com/PavelZinchenko/event-horizon-main/assets/65084389/258cee0a-ddd5-4938-8c72-bef9bd40ac47)

**Comment by Kipyatochkov** [comment]
UPD: the editor does not work only if "DatabaseVersionMinor": 3

**Comment by Kipyatochkov** [comment]
UPD №2: however, you can't edit anything anyway

**Comment by PavelZinchenko** [comment]
I updated the archive and added the latest database to it
