### ISSUE TITLE
Localization problems

### ISSUE THREAD

**Issue by GawayPilot** [PavelZinchenko/event-horizon-main#157]
After the first launch of the game (save), the localization either works fine or breaks down again.

After repeated launches, you have to go into the settings and switch through languages to make it work
![untitled](https://github.com/PavelZinchenko/event-horizon-main/assets/158202454/2322db99-2a43-46b8-b104-2641822b9123)

**Comment by juh9870** [comment]
Please use English, it will make it easier for other people to track active issues.
