### ISSUE TITLE
RFC: Ammunition trajectory

### ISSUE THREAD

**Issue by juh9870** [PavelZinchenko/event-horizon-main#159]
This is a request for comments. I propose my changes and unresolved questions, and once enough feedback is gathered and questions are resolved, I will proceed to make a PR, implementing changes that were discussed. This approach fosters better communication regarding major changes, and allows for fearless PR implementation, knowing that the changes are at least desirable, and we are moving in the right direction.

# Summary
Allow advanced ammunition to specify custom flight trajectory via expressions.

# Motivation
Mod makers have shown interest in implementing weapons with an unusual flight patterns (curving, sinusoidal, etc.), which currently requires messing with recursion and rotation of newly spawned ammo. This greatly limits what can be done, and how long it can be sustained (recursion is limited to 100 right now).

# Approach
Custom trajectory is clearly going to be a new Controller type, and the groundwork for implementing that is already done.
Proposed trajectory structure:
- `X(lifetime)` formula of the X offset at during the given moment in bullet lifetime, relative to the bullet origin.
- `Y(lifetime)` formula of the Y offset at during the given moment in bullet lifetime, relative to the bullet origin.
- `Rotation(lifetime)` formula of the bullet rotation at the given moment in bullet lifetime, relative to the bullet initial rotation.

Now the question is, how will it be declared in the ammunition file?

## 1. New bullet type
This approach creates a new bullet type — `Trajectory`, which mostly acts like Static, but has extra expression fields to control the trajectory.
In this approach, bullet origin is defined as the position and rotation at which the bullet was initially spawned.
### Pros:
- In line with other current examples of custom controllers, like Magnetic and Homing
### Cons:
- Requires maintaining an addition `BulletType`, and the codebase is already pretty messy with them.

## 2. New Action
This approach creates a new bullet Action, which allows adding or changing bullet controller, with `TrajectoryController` being one of the possible options.
In this approach, bullet origin is the position and rotation the bullet was in during the Action activation.
### Pros:
- Easier to implement, there is no need to account for all possible implications of new `BulletType`, we just change the controller.
- This approach allows for an easy extension with extra controller types later down the line
- Allows changing controller mid-flight, allowing for even more behavior customization.
### Cons:
- Goes against the current approach where different controllers get different Bullet Types.
- A bit cumbersome to define the initial controller. You need to have the `Created` trigger setting on the controller.
### Unresolved questions:
Need to figure out how this would interact with bullets that already have controllers. What happens when a mod author uses this trigger on a `Homing` bullet?

Cons and unresolved questions of this approach can be addressed if option 3 is picked:

## 3. Split BulletType into separate fields
Currently, `BulletType` is a bit arcane in what it does. Some variations define general bullet behavior (Static, Continuous), while others are just Controllers (Homing, Magnetic). This approach decides to ditch `BulletType` in it's entirety, and instead split it into relevant fields, for example:
- `boolean IgnoreParentVelocity` - replaces whole `Static` bullet type.
- `boolean StickToParent` - replaces whole `Continous` bullet type.
- `Controller` - determines which controller is used for the bullet.

Field list may be changed during implementation, but this is a general idea.

### Pros:
- Reduces amount of "magic" values in database, which are not very clear to new mod makers.
- This approach also allows for an easy extension with extra controller types later down the line.
- If this approach is picked, approach (2) will be extremely easy to implement as an addition later, we just swap the controller in the Action
### Cons:
- This is a breaking change and will require migration code. I'm not yet knowledgeable enough in it, so I might need help at the later stages of this PR to implement migrations.
---

My personal pick is the third approach, but I want to hear from other people and the developer first.

**Comment by JVDP-LNS** [comment]
The third approach is the most appealing, as it allows a huge amount of different combinations of ammunition settings, in addition to the main topic of variable ammunition trajectory. It would be great if it is implemented.

**Comment by Zen9890** [comment]
Third approach is definitely the best as it will also provide some other basic tools that modders longed for (ignore parent velocity bool for example) and will provide us with customizable controllers so we arent stuck to the hardcoded stuff

**Comment by juh9870** [comment]
Missiles would just be a Homing controller from what I see right now

**Comment by PavelZinchenko** [comment]
The 3rd option I like the most. As for the migration part, I'd prefer to do it myself.

**Comment by juh9870** [comment]
Amazing! Then I will start implementing the feature, and will leave migration up to you.
