### ISSUE TITLE
Components randomly change colour in build editor upon entering any of the components tab

### ISSUE THREAD

**Issue by Zen9890** [PavelZinchenko/event-horizon-main#167]
![image](https://github.com/PavelZinchenko/event-horizon-main/assets/62694017/a2307460-7582-47d5-91f6-7d408922e441)
This issue persists untill player either opens any component and closes its window, or scrolls components tab untill bugged components are not visible and scrolls back

**Comment by PavelZinchenko** [comment]
I believe it's already been fixed in 2db62a0
