### ISSUE TITLE
Broken battles

### ISSUE THREAD

**Issue by Kipyatochkov** [PavelZinchenko/event-horizon-main#169]
If a module without a layout (we call such modules phantom modules) is installed on the enemy's ship, the battle does not begin, and the quest goes into waiting (and it also blocks other quests).
But please do not remove the ability to make such modules, they allow to make built-in characteristics for specific builds.

**Comment by PavelZinchenko** [comment]
I couldn't reproduce the bug. I removed layout from the titanium armor, but all battles started without any problems. Need more details or a test mod
