### ISSUE TITLE
[Improvement] Pavel, please make custom tails for the Worms faction. 

### ISSUE THREAD

**Issue by VladSuhanOFF** [PavelZinchenko/event-horizon-main#185]
Custom tails are very necessary for bio-ships!

**Comment by PavelZinchenko** [comment]
Guys, if you really want some feature, click 👍 or ❤️. I'll work on the most liked ones first.

**Comment by CrispyToken** [comment]
Please correct me if I'm wrong, but is this not a duplicate of https://github.com/PavelZinchenko/event-horizon-main/issues/13 ?
If not, please clarify.
