### ISSUE TITLE
Option to disable game image editing

### ISSUE THREAD

**Issue by GawayPilot** [PavelZinchenko/event-horizon-main#186]
With the latest updates it is no longer possible to go beyond the cells of the layout, the pictures are clearly adjusted by the game to the cells and this can interfere in some cases
And also the game cuts off the transparent background, which could be used intentionally

С последних обновлений больше нельзя выйти за рамки клеток лейаута, картинки чётко подгоняются игрой в клетки и это может помешать в некоторых случаях
А также игра обрезает прозрачный фон, который мог бы использоваться намеренно

**Comment by juh9870** [comment]
Are you talking about components? If yes, it might be better to introduce more sprite options rather than only Color. I also had some cases where tweaking was required to properly position complex sprites

**Comment by PavelZinchenko** [comment]
Is it still an issue after resolving #188 ?
