### ISSUE TITLE
Restore the Full functionality of modules without cells

### ISSUE THREAD

**Issue by GawayPilot** [PavelZinchenko/event-horizon-main#188]
With the new updates, modules without cells can no longer use any grid, it is limited to 1x1 as far as I understand.
Because of this, some cosmetic items using this feature have fallen off.
I tried to adapt, but it turned out that they are also displayed on top of everything, previously those that were placed first were displayed (you could put something else on them, and it would be displayed above them)

С новыми обновлениями модули без клеток более не могут использовать любую сетку, она ограничена 1х1 на сколько я понял. 
Из-за этого слетели кое-какие косметические штуки использующие эту особенность.
Я пытался адаптировать, но выяснилось что они еще и поверх всего отображаются, раньше отображались те которые были первее поставлены (на них можно было поставить что-то еще, и оно бы отображалось над ними)

**Comment by juh9870** [comment]
Can you please show example of "cosmetic usage" you are talking about?

**Comment by GawayPilot** [comment]
> Can you please show example of "cosmetic usage" you are talking about?

![NormalIcons](https://github.com/PavelZinchenko/event-horizon-main/assets/158202454/619921ad-99bb-485a-9aa8-872df1001042)
![BrokenIcons](https://github.com/PavelZinchenko/event-horizon-main/assets/158202454/e856cb33-7c96-453d-893c-55553f8fe6ea)

Just custom sprites for cells, but these are modules without cells. Now is broken.
I think it’s easier to ask for something that worked before than to ask for custom cells

**Comment by PavelZinchenko** [comment]
I need your mod for testing. Could you please attach it or send by email?

**Comment by juh9870** [comment]
> I think it’s easier to ask for something that worked before than to ask for custom cells
I strongly disagree with this line of thinking. What we had before are hacky solutions that we used in the absence of an adequate solution, so it's much better to tackle the core issue, rather than trying to bring the hacks back.
