### ISSUE TITLE
Most sounds don't work(mobile version)

### ISSUE THREAD

**Issue by OtakuDeith** [PavelZinchenko/event-horizon-main#202]
Все звуки, кроме континуусных не работают на мобильной версии.
All sounds except continuum ones (lasers, map flight) do not work(mobile version).

upd: похоже не на всех устройствах такая проблема существует, но как минимум на realme 10 эта проблема есть.
upd: It seems that not all devices have this problem, but at least realme 10 has this problem.

https://cdn.discordapp.com/attachments/1186664576620707891/1206356838866751508/Record_2024-02-11-23-49-56_daeaaba1e9024222608ccbc1fe1ad59e.mp4?ex=65dbb65b&is=65c9415b&hm=b5a769c816570e20b2336d99f93f5a6bc0550b5cd87e70ad040de0a0585d41ea&

**Comment by ViviX12** [comment]
Sound files have some specific requirements to work properly, which can be an issue, but your statement is false. Do some research on the bugs you bring up before opening issues.

**Comment by OtakuDeith** [comment]
похоже не на всех устройствах такая проблема существует, но как минимум на realme 10 эта проблема есть.
upd: It seems that not all devices have this problem, but at least realme 10 has this problem.

**Comment by OtakuDeith** [comment]
После релиза 1.11 все звуки работают, проблема закрыта.
After release, all sounds work, the issue is closed.
