### ISSUE TITLE
Pause button spam permanently freezes battle

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#22]
Combat can permanently freeze when pause button is repeatedly spammed too fast. Only way to fix is retreating and reentering the battle.

**Comment by juh9870** [comment]
Fix:
https://github.com/PavelZinchenko/event_horizon/commit/cbd5560a2fa176fe622d7221909d743c41abbe10
https://github.com/PavelZinchenko/event_horizon/commit/8fe1f27e73df2ec34666d9af4d3ff754140e3507
