### ISSUE TITLE
Окно с подтверждением атаки на базу появляется когда в нём нет смысла / A window confirming an attack on the base appears when it isn't needed

### ISSUE THREAD

**Issue by Inedilarion** [PavelZinchenko/event-horizon-main#221]
А конкретно, когда у базы и так минимальная репутация, и у баз "враждебных" фракций, не имеющих репутации

Specifically, when the base already has minimal reputation, and when attacking bases of “hostile” factions that have no reputation

**Comment by juh9870** [comment]
Please use English when describing issues, would make it easier for others to search and keep track of issues

**Comment by Kipyatochkov** [comment]
Это решит проблему / this will solve the issue: [CaptureStarbase.json](https://github.com/PavelZinchenko/event-horizon-main/files/14309122/CaptureStarbase.json)
