### ISSUE TITLE
Вражеские корабли не пытаются как-либо противодействовать невидимому игроку / Enemy ships do not try to counteract the invisible player in any way

### ISSUE THREAD

**Issue by Inedilarion** [PavelZinchenko/event-horizon-main#229]
Раньше вражеские корабли летели в сторону игрока, либо постоянно двигались, усложняя стрельбу по себе

Previously, enemy ships flew towards the player, or were constantly moving, making it difficult to shoot them

https://github.com/PavelZinchenko/event-horizon-main/assets/66635560/80f1c411-826e-40a8-aa09-a653f0101be3

**Comment by PavelZinchenko** [comment]
Not a bug. Enemies can't detect invisible player. If a player comes too close, they will start attacking.
