### ISSUE TITLE
Weapon barrels order is incorrect on multiple vanilla ships

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#23]
Multiple ships across the vanilla game database have their barrels configured in the wrong order as seen in the below example:
![187449198-7ee3feff-ab15-444a-9031-28c9747caf5f](https://github.com/PavelZinchenko/event-horizon-main/assets/61762578/e138f0e8-565f-4747-9f15-997e14460ed7)
![187449748-268aae93-bded-4efe-9f6c-5b7d624561cb](https://github.com/PavelZinchenko/event-horizon-main/assets/61762578/e11fbebe-5f0c-4f6e-bcc1-27f09871e424)
![187450343-868d878f-a4b0-4bc9-9776-40e37c14aa3e](https://github.com/PavelZinchenko/event-horizon-main/assets/61762578/43b58b55-0f15-4076-8411-e1359a281aad)

**Comment by juh9870** [comment]
Fix: https://github.com/PavelZinchenko/event_horizon/commit/acfe588ccb96c82cd5e2de3ec25bcde38cd140a2
