### ISSUE TITLE
 Ship info panel and build editor use different fonts for weapon types

### ISSUE THREAD

**Issue by Zen9890** [PavelZinchenko/event-horizon-main#234]
![image](https://github.com/PavelZinchenko/event-horizon-main/assets/62694017/9502cfaf-ac79-4dd5-9f95-8fe2f2bfe320)
![image](https://github.com/PavelZinchenko/event-horizon-main/assets/62694017/3a28b382-2f49-4958-86d2-f2b54d2b68ce)
My proposal is to bring back bicubik font in ship build editor, because new font sometimes looks uncanny, especially, for example, with M type slots

**Comment by PavelZinchenko** [comment]
I enabled mipmaps. Now, the text appears smoother. Unlike the old ship editor, the ship model is a mesh, not part of the UI. It uses a baked font texture instead of a font. Using bicubic would be difficult to implement due to variable character widths.
