### ISSUE TITLE
Improved crafting options are enabled for items with no possible modifiers

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#24]
Improved quality buttons are still active for modules with no possible modifications. Crafting such improved item produces an identical copy of the standard item which is displayed separately from the standard item in the inventory.
![261855658-320b4c30-db4f-46b3-8187-cbbf3a57c8c5](https://github.com/PavelZinchenko/event-horizon-main/assets/61762578/3c5052cc-16e6-4224-822b-1a4829fc1e0e)

**Comment by juh9870** [comment]
Fix: https://github.com/PavelZinchenko/event_horizon/commit/c8f31f40656221918b436dda4fc8f238cec4d9e5
