### ISSUE TITLE
Survival has to be fully finished to get rewards

### ISSUE THREAD

**Issue by Pomeha-TLA** [PavelZinchenko/event-horizon-main#252]
Yes 
It doesn't matter how much if the ships you killed
If you died you won't get any reward no matter what but in survival it supposed to be _more enemies killed = rewards_

**Comment by PavelZinchenko** [comment]
Make sure that you have `SurvivalCombatRules` in `GalaxySettings` and `LootCondition` set to `Always`. I tested it and got loot after killing several ships.
