### ISSUE TITLE
Stat numbers in ship constructor can overflow

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#27]
If the ship's stats are too high, the HP and energy stats at the bottom show -2147483648.

**Comment by juh9870** [comment]
Series of commits on this:
- Initial fix for numbers overflow in constructor by formatting them https://github.com/PavelZinchenko/event_horizon/commit/c120864dd4a4de2532bca6cb912b42c8b121677a
- Better formatting for large numbers https://github.com/PavelZinchenko/event_horizon/commit/e68bbf812bd8c7b5cf3934abd59612820a0c48e3
- Decimal dot visibility fix https://github.com/PavelZinchenko/event_horizon/commit/72a639a6ff923ad60ebc46559c29a4da4d34155e
