### ISSUE TITLE
Allow enemies in quests exceed maximum ship level limit with some special option

### ISSUE THREAD

**Issue by Seneriel** [PavelZinchenko/event-horizon-main#279]

**Comment by CrispyToken** [comment]
FYI: 
If you would like to allow enemies in quests to have a higher level limit while still keeping regular enemies below a certain lower threshold, you can achieve this via editing the "EnemyLevel" expression under Galaxy.json while leaving MaxEnemyShipsLevel as maximum for enemies in quests.
