### ISSUE TITLE
[Bug] Some game textures are not working properly

### ISSUE THREAD

**Issue by 1distilledwater** [PavelZinchenko/event-horizon-main#280]
The game version that discovered this issue is 1.11.1build1660 on the mobile phone (This issue still exists in version 1.11.2build1676). **In my long-term observation, this problem occurs in some specific resolution images. For example, when applying the image of 340X340 to a spaceship.** I tried to modify the images of other sized spaceships to 340X340, and sure enough, they all made mistakes.

I noticed that some icons did not work as expected, and they showed varying degrees of deformation and missing information. I noticed that this bug also appears in version 1.11.1build1663 PC, but the probability is much lower. I checked my database and tried to delete information that was too large to reduce the size of the mod, but this didn't work. These incorrect icons are not all very large images, some of them are only 54kb, 340X340 pixels. 
Below is a video about this issue.

https://github.com/PavelZinchenko/event-horizon-main/assets/153053055/324d3b33-b297-4e67-ad61-0746a2fb300d

The items attached on both sides of the chronos in the video are fixed textures.
At the beginning of the video, there is clearly a missing piece in the center of the icon of the enemy spacecraft. As both sides approached, the texture returned to normal. Different picture quality settings in the game also have an impact on the aforementioned issues. In low image quality situations, larger icons cannot even return to normal when two enemy or friendly ships approach, but instead remain distorted or missing. If the field of view reaches its maximum, it is often more prone to the above-mentioned problems.

The following are the icons that should have been working properly in the video.
![1703](https://github.com/PavelZinchenko/event-horizon-main/assets/153053055/5b417c0f-34f0-404b-aa7b-b6ec03117abb)
![lszj](https://github.com/PavelZinchenko/event-horizon-main/assets/153053055/fa07b682-f681-4ce0-b14f-ae409d581d65)
In the above two images, the image of the spaceship has becomed to the following.
![2024-03-06 155810](https://github.com/PavelZinchenko/event-horizon-main/assets/153053055/c0cf95ab-9407-4f23-a9ad-a67a626c96a7)

The following is the video recording on the PC.
https://github.com/PavelZinchenko/event-horizon-main/assets/153053055/59494dca-79bc-40bf-8185-8a594addbe22
Here are the textures I used.
![1102](https://github.com/PavelZinchenko/event-horizon-main/assets/153053055/8c190c19-72d6-4d97-97e6-a06e9088fc21)

**Comment by juh9870** [comment]
May be related to #313

**Comment by PavelZinchenko** [comment]
Fixed this issue. However, try using power-of-two sized images such as 256x256, 512x512, or 1024x1024. GPUs are optimized for these dimensions, resulting in better performance and lower memory usage.

**Comment by PavelZinchenko** [comment]
https://github.com/PavelZinchenko/event-horizon-main/commit/446dcf2a025a2dae145548b29bf172a6c28a6e6e

**Comment by 1distilledwater** [comment]
> Fixed this issue. However, try using power-of-two sized images such as 256x256, 512x512, or 1024x1024. GPUs are optimized for these dimensions, resulting in better performance and lower memory usage.

Thank you for your reminder.
