### ISSUE TITLE
RFC: Randomized Components

### ISSUE THREAD

**Issue by juh9870** [PavelZinchenko/event-horizon-main#301]
This is a request for comments. I propose my changes and unresolved questions, and once enough feedback is gathered and questions are resolved, I will proceed to make a PR, implementing changes that were discussed. This approach fosters better communication regarding major changes, and allows for fearless PR implementation, knowing that the changes are at least desirable, and we are moving in the right direction.
# Summary
A new type of component, which transforms into a random component from the predefined list upon entering the battle.

# Motivation
Currently there is no good way to introduce variation into enemy builds without creating way too many of them, which is both tedious, as well as messes up with enemy spawn proportions. This change would allow for easy and controlled variation in stats, or even devices or weapons of enemy builds.

# Approach
## Database changes
This new type of component doesn't actually need most of the component fields (stats, device, weapon, etc.), so this change will turn Component into a switch-object, via new `Type` field. This new component type is planned to have the following fields:
- `Name`, `Icon`, `Color` - same as regular component, used to display this component in the build editor
- `Variations` - list of the `RandomComponentVariant` that this component can turn into

### `RandomComponentVariant` struct
- `Component`: ID of the component
- `Modification`: ID of the modification
- `Qualiy`: Quality of the modification
- `Weight`: RNG Weight for this variant to get picked

This approach also opens a way for adding more "technical" component types in a future.
## Technical info
Component replacement should reuse the same RNG seed that is used by fleet generation, to avoid player cheesing the hard fight by rerolling until the enemy gets weaker or more convenient build variation.

Component replacement does not check for slot type, shape, or weapon type of the replaced component. This may create constructor-invalid builds (aka 1x1 component getting replaced with 3x3 when there is no space for it), but this is not an issue because replacement happens right when calculating devices/weapons/stats during combat, and does not actually affect the build in the constructor.

> This means that it is even safe to give such components to player, tho I imagine it would be hard to balance to avoid reroll RNG.

# Open questions
1. Should multiple of the same "random component" installed on a ship be randomized into the same variant (`rng_seed = combat_seed * ship_id`), or should each component roll RNG individually (`rng_seed = combat_seed * ship_id * component_index`)?
  > For example: `RandomGun` can be `ProtonTorpedo`, `RocketLauncher`, or `LaserBeam`. If you install 3 of `RandomGun` on a ship, should all 3 become the same gun, or should each of them roll random individually and become different guns?
2. Maybe adding a new field to control behavior from (1) is better (`bool IndividualRandom`)? Should it be `true` or `false` by default?

**Comment by Inedilarion** [comment]
В первом вопросе мне больше нравится общий фактор для корабля, чтобы разом менялись пушки и объём энергии к ним, например. Но новый параметр будет лучше, отвечая на второй вопрос. И с общим фактором по умолчанию

**Comment by juh9870** [comment]
It doesn't work this way, different "random component" types have independent random and can't be reasonably synced. Open questions are about random in terms of multiple of the same "random component" type getting installed on a ship.
For example: `RandomGun` can be `ProtonTorpedo`, `RocketLauncher`, or `LaserBeam`. If you install 3 of `RandomGun` on a ship, should all 3 become the same gun, or should each of them roll random individually and become different guns?

**Comment by Inedilarion** [comment]
Same

**Comment by PavelZinchenko** [comment]
I thought about creating a random build generator to add more variety. It would include settings to adjust the outcomes. However, this task is more complicated. A RandomComponentVariant is actually a slot in the build template that can be filled with a component from a predefined set.
The variability in component sizes and energy costs could lead to balance challenges. Ensuring that all possible outcomes are equally viable and balanced could require extensive testing and adjustments. It can easily lead to non-viable builds.
Also It will increase the complexity of the component system.
I'd prefer to choose another solution.
What comes to my mind is a build generator alongside build templates, which incorporate parameters such as the desired ship characteristics, modules, or weapons to include, among others. This generator could control the outcome to ensure the build is viable.
