### ISSUE TITLE
Incorrect discounted workshop level requirements display

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#31]
Workshops display incorrect/unmodified level requirements under listed items after workshop level captain skill is purchased.
![187039648-12aa2749-beda-4068-80de-31b859f4ea1d](https://github.com/PavelZinchenko/event-horizon-main/assets/61762578/4a50e10a-ff56-4bcc-96a7-17637cdcf513)

**Comment by juh9870** [comment]
Fix: https://github.com/PavelZinchenko/event_horizon/commit/3bf4e1e4c95324877916f7283a7f857c27774a0f
