### ISSUE TITLE
Component and ship textures becoming warped

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#313]
Does not affect all components or ships, only a select few from my experience.

**Steps to reproduce the issue**
No explicit steps have been taken to trigger this issue.
Some ship sprites are warped in the hangar as well as in the ships list, while some components are warped in the build editor.
Zooming out to a degree may be required to trigger component sprite warp.

**Expected behavior**
Component and ship sprites do not warp

**Actual behavior**
They do.

**Your game version and operating system**
1.11.1 Build 1666
Android 13

![image](https://github.com/PavelZinchenko/event-horizon-main/assets/61762578/56e16e54-b139-4296-b572-df7a3ab3a8bd)
![image](https://github.com/PavelZinchenko/event-horizon-main/assets/61762578/a66269b3-a06b-47af-a8f4-a04f2acf0aee)
![image](https://github.com/PavelZinchenko/event-horizon-main/assets/61762578/f07991f5-8ea0-4790-ae21-7f2e216e6d1e)

**Comment by juh9870** [comment]
May be related to #280

**Comment by juh9870** [comment]
https://drive.google.com/file/d/1QjxLUZvuMEmUD92R3YgNp7djbo3G1D5W/view?usp=sharing

Example mod that has this issue on the android. Instructions from the author:
> I have created a small mod that generates this bug again. You only need to use the mother ship (instead of the initial spaceship) to enter battle and you will see this terrible bug.
This mod will encounter the aforementioned bugs on the mobile version 1.11.1 (build 1666), while everything is normal on the PC version.
