### ISSUE TITLE
[Bug] Where is IFunction,Variant, Expression, and CodeWrite namespace???

### ISSUE THREAD

**Issue by zkip** [PavelZinchenko/event-horizon-main#325]
When I first opened the project, it can't run.
When I tried to fixed the problem with ObscuredInt missing, there were more errors.
I doubt that this project will be easy for anyone else to run.

![image](https://github.com/PavelZinchenko/event-horizon-main/assets/19899022/966c6b18-3245-467f-8f5e-fd03d08c8c9f)

**Comment by juh9870** [comment]
You did not pull git submodules. See https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by zkip** [comment]
$ git submodule update --init --recursive
Cloning into 'C:/Users/zpox/projects/event_horizon_fork/event-horizon-main/Assets/ModulesPrivate'...
info: please complete authentication in your browser...
remote: Repository not found.
fatal: repository 'https://github.com/PavelZinchenko/event-horizon-private-stuff/' not found
fatal: clone of 'https://github.com/PavelZinchenko/event-horizon-private-stuff' into submodule path 'C:/Users/zpox/projects/event_horizon_fork/event-horizon-main/Assets/ModulesPrivate' failed
Failed to clone 'Assets/ModulesPrivate'. Retry scheduled
Cloning into 'C:/Users/zpox/projects/event_horizon_fork/event-horizon-main/Assets/ModulesPrivate'...
info: please complete authentication in your browser...
remote: Repository not found.
fatal: repository 'https://github.com/PavelZinchenko/event-horizon-private-stuff/' not found
fatal: clone of 'https://github.com/PavelZinchenko/event-horizon-private-stuff' into submodule path 'C:/Users/zpox/projects/event_horizon_fork/event-horizon-main/Assets/ModulesPrivate' failed
Failed to clone 'Assets/ModulesPrivate' a second time, aborting

I can't access some libraries, are they private？

**Comment by juh9870** [comment]
yes, `ModulesPrivate` is private, but the game uses fallbacks when it is not present, so you can skip it

**Comment by zkip** [comment]
When I removed the submodule it worked fine, thank you.
