### ISSUE TITLE
Switch in ship file to disable cell expansion

### ISSUE THREAD

**Issue by Seneriel** [PavelZinchenko/event-horizon-main#331]
Возможность отключить расширение клеток для конкретных кораблей параметром в файле, такая же возможность в общих настройках имеющая меньший приоритет чем ранее упомянутая

**Comment by juh9870** [comment]
Please use english language, it makes it easier for other people to understand the topics and give suggestions, as well as avoid duplicate suggestions

**Comment by Seneriel** [comment]
What I typed non-English is just a bit more elaborated title for easier understanding, also Pavel said I can use Russian in github too

**Comment by Seneriel** [comment]
Closed accidentally
