### ISSUE TITLE
[Request] Add a "Voting" section where the final proposals will be included

### ISSUE THREAD

**Issue by Bezbasheniy** [PavelZinchenko/event-horizon-main#348]
Add a "Voting" section where the final proposals will be included. And subsequently, to accept for implementation only those proposals that were supported by at least five people. Such a system will serve as a safeguard against obviously bad and unbalanced ideas, and subsequently reduce the burden on the developer, as well as reduce the number of users dissatisfied with innovations

**Comment by Snowgods** [comment]
Disagree about it being a  safeguard against unbalanced ideas... It's more likely to be a cause of them as most players will vote for whatever makes their build strongest.
