### ISSUE TITLE
[BUG] The beam made with parameter ammunition has failed.

### ISSUE THREAD

**Issue by 1distilledwater** [PavelZinchenko/event-horizon-main#352]
The game version is 1.11.2 build 1674

**Comment by juh9870** [comment]
Hello, please attach ammunition files, and a detailed description of how it was intended to function and what went wrong. In the current state, there is not enough info to determine the issue.

**Comment by 1distilledwater** [comment]
> Hello, please attach ammunition files, and a detailed description of how it was intended to function and what went wrong. In the current state, there is not enough info to determine the issue.
[test.zip](https://github.com/PavelZinchenko/event-horizon-main/files/15483133/test.zip)
Even the simplest beam made from parameter ammunition cannot function properly in version 1.11.2build1674.
