### ISSUE TITLE
PiercingLaser plays only 1 visual effect even when it is in contact with multiple targets.

### ISSUE THREAD

**Issue by JVDP-LNS** [PavelZinchenko/event-horizon-main#363]
![image](https://github.com/PavelZinchenko/event-horizon-main/assets/112297738/84a5224e-e682-4e32-aec7-c5ed6d1fcd70)

 A continuous beam using the PiercingLaser bullet which has a trigger to PlaySfx on Hit, plays the effect only on the closest target to laser origin, although the effect should appear on all the targets the laser is in contact with.

**Comment by PavelZinchenko** [comment]
That's how PlaySfx works; it can play only one effect at a time. Use SpawnStaticSfx instead, as it is used in the Annihilation Ray

**Comment by JVDP-LNS** [comment]
I have tried this and SpawnStaticSfx does indeed solve this issue. I had assumed SpawnStaticSfx's only function is to play an effect which has no movement.

**Comment by PavelZinchenko** [comment]
Enabling OncePerCollision flag allows multiple effects to be played

**Comment by JVDP-LNS** [comment]
Thanks for the feature 👌
