### ISSUE TITLE
Turning rate/Forward acceleration/Angular acceleration is limited to 5 in databased mods

### ISSUE THREAD

**Issue by Pomeha-TLA** [PavelZinchenko/event-horizon-main#365]
![Screenshot_20240602-083949_1](https://github.com/PavelZinchenko/event-horizon-main/assets/152905218/0d5649b5-7b8c-4c07-9617-9325a9f7f4bd)
In mod development confirmed there's speed limit 30 but game turns it into 5 same as forward speed from 30 to 20

**Comment by Zen9890** [comment]
Issue is not quite that, game defaults new acceleration settings to 5 instead of the vanilla database value of 400, changing how ships fly arround in result drastically
