### ISSUE TITLE
[BUG] The position of the child parameter ammunition generated by the parent ammunition has abnormally shifted.

### ISSUE THREAD

**Issue by 1distilledwater** [PavelZinchenko/event-horizon-main#373]
The game version is 1.12.0 build1692

In advanced ammunition, parameter ammunition (_I checked my other weapons again and found that a few weapons that did not use parameter ammunition also had issues_.) generated by ordinary parent ammunition no longer works as normally as previous versions, and their generation positions deviate from the expected positions.

This is the weapon file that caused this issue and needs to rely on the default database to open it.
[Test Weapons.zip](https://github.com/user-attachments/files/15527963/Test.Weapons.zip)

**Comment by VladSuhanOFF** [comment]
I support you!

**Comment by 1distilledwater** [comment]
Some weapons in my database that did not use parameter ammunition also generated this bug.
