### ISSUE TITLE
Quick battle asteroid damage is tied to distance from home in save

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#38]
When the player enters a quick battle while a save is loaded, the asteroids in quick battle will deal increased collision damage based on the player's distance from home in the loaded save. Asteroids in quick battle can sometimes instakill ships.

**Comment by juh9870** [comment]
Fix: https://github.com/PavelZinchenko/event_horizon/commit/3c791b611b7646304da37351dfa24d941c1603ef
