### ISSUE TITLE
[BUG] Some Effects of advanced ammunition are broken and are not displayed in battle.

### ISSUE THREAD

**Issue by lXvladXl** [PavelZinchenko/event-horizon-main#380]
I noticed that almost all the effects in the game were broken for some reason.
After update 1.11.2, the effects stopped being displayed in battle.
![изображение_2024-06-05_162421951](https://github.com/PavelZinchenko/event-horizon-main/assets/117071735/aee45bcb-5756-4642-b0cb-fd21700e59c0)

https://github.com/PavelZinchenko/event-horizon-main/assets/117071735/d8105380-56b7-403a-b6fb-99dd939e2d95

(There must have been effects)

**Comment by lXvladXl** [comment]
https://github.com/PavelZinchenko/event-horizon-main/assets/117071735/a8cdb3c0-3e55-474e-a3cb-d1e206e55bd9

In old version

**Comment by PavelZinchenko** [comment]
Could you attach the mod file for testing?

**Comment by lXvladXl** [comment]
Okay
[17668 Kladenets.zip](https://github.com/user-attachments/files/15594157/17668.Kladenets.zip)
This is a full weapon file with sprites, effects and sounds

**Comment by lXvladXl** [comment]
But it also happening on other weapons too

**Comment by lXvladXl** [comment]
By the way, for some reason the effects still work when set as a weapon shot effect

**Comment by PavelZinchenko** [comment]
Можно, но лучше на английском. Эффекты не показываются потому что у них Lifetime 0

Effects do not work because their lifetime is 0

**Comment by lXvladXl** [comment]
Is this a new Important value?

**Comment by lXvladXl** [comment]
![Screenshot_20240605-205319](https://github.com/PavelZinchenko/event-horizon-main/assets/117071735/5282d203-4971-4281-b489-66686e2610c2)
But there’s already lifetime

**Comment by PavelZinchenko** [comment]
They last for the duration specified by the lifetime in seconds. Did it work before the update?

**Comment by PavelZinchenko** [comment]
I just changed the lifetime, and the effect started working

**Comment by lXvladXl** [comment]
As you can see, before the update everything worked, I didn’t touch anything and only now everything went wrong

**Comment by lXvladXl** [comment]
Need to change the lifetime in ammo?

**Comment by PavelZinchenko** [comment]
I changed the lifetime in the file '70 timer.json,' and they seem to work.

**Comment by lXvladXl** [comment]
In that case, I'll take a closer look, but before everything worked somehow without this, strange...

**Comment by PavelZinchenko** [comment]
You need to specify the exact lifetime; otherwise, they will last only as long as the bullet that triggered them. Since your bullet triggers them right before it expires, the effects do not show.

**Comment by PavelZinchenko** [comment]
This was changed in 1.12

**Comment by PavelZinchenko** [comment]
I made some fixes. It should now work as it did before the update

**Comment by lXvladXl** [comment]
Thank you
