### ISSUE TITLE
[Enhancement]Adding a friends system for online functions

### ISSUE THREAD

**Issue by Willstuff1111** [PavelZinchenko/event-horizon-main#418]
So that you can play with friends

Edit: also, how do I add the enhancement tag?

**Comment by TheGreyRadical** [comment]
Bro doesn't know how code works :skull:. Seriously though, your request is very vague. The closest game ever got to online was long deprecated Bluetooth pvp battles, and arena which is PVE with player builds. And you suggest a whole online system which would need servers and more. Please do not clog up the issues with such unrealistic requests.

**Comment by Willstuff1111** [comment]
I found a projects page and apparently they are planning on adding it so it's not unrealistic because they said it themself
