### ISSUE TITLE
[Help Request] How do i mod

### ISSUE THREAD

**Issue by Willstuff1111** [PavelZinchenko/event-horizon-main#422]
I've seen so many questions that are can you add this to modding but I don't understand how you start and get to that point

**Comment by TheGreyRadical** [comment]
This place is purely for suggestions by people knowing what they ask to add/improve/fix, not for such questions. If you need help, go to official discord server of the game and ask there. Or actually try modding without any help, this also may work.

**Comment by Seneriel** [comment]
Modding without help may seem cool and stuff, but I got to remind you that we are no longer in dark database ages where only a few selection of people could mod and even fewer of them had extensive knowledge. So feel free to ask about anything regarding modding https://discordapp.com/invite/yFFvF7m
