### ISSUE TITLE
Installed active modules on ships past 64 become non-functional

### ISSUE THREAD

**Issue by CrispyToken** [PavelZinchenko/event-horizon-main#45]
Once 64 active modules (weapons / devices / dronebays) are installed on a shipbuild, any installed active module past this number will be non-functional.

**Comment by juh9870** [comment]
Pretty easy fix: https://github.com/PavelZinchenko/event_horizon/commit/a5676e90799fd4d2911a3b213ae8b02fd8fead2f
https://github.com/PavelZinchenko/event_horizon/commit/094e11719bfbd2540aadd29bc743b71806f3214b
